# Header
menu:
  首页: /
  所有文章: /archives
  #随笔: /tags/runtime
  #其他: /
  #other: /

# SubNav
subnav:
  github: "https://github.com/zzyspace"
  weibo: "http://weibo.com/u/2008464051"
  facebook: "https://www.facebook.com/profile.php?id=100009454526965"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  #mail: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
baidu_tongji: true
favicon: /favicon.png

#你的头像url
avatar: "https://github.com/zzyspace/BlogBackup/raw/master/hexo/others/avatar.jpg" #"http://tp4.sinaimg.cn/2008464051/180/40011990326/1"
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
#  奥巴马的博客: http://localhost:4000/
#  卡卡的美丽传说: http://localhost:4000/
#  本泽马的博客: http://localhost:4000/
#  吉格斯的博客: http://localhost:4000/
#  习大大大不同: http://localhost:4000/
#  托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 不会摄影的iOS开发者不是好吉他手
